---
title: "Back to School"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Dependency
```{r}
library(tidyverse)
library(dplyr)
```
### Read CSV file
```{r}
MechaCar_mpg_table <-read_csv("resources/MechaCar_mpg.csv")
```
### Preview tibble
```{r}
head(MechaCar_mpg_table)
```

### Create a linear model
```{r}
model<-lm(mpg ~ vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD,MechaCar_mpg_table)
model
```

### Generate summary statistics
```{r}
summary(model)
```
```{r}
# import and read Suspension_Coil.csv
Suspension_Coil_table <-read_csv("resources/Suspension_Coil.csv")
Suspension_Coil_table
```
```{r}
# Total summary data frame
total_summary<-Suspension_Coil_table%>%summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI),.groups='keep')
total_summary
```


```{r}
lot_summary<-Suspension_Coil_table%>%group_by(Manufacturing_Lot)%>%summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI),.groups='keep')
lot_summary
```


```{r}
```


```{r}
```


```{r}
```

